export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const TOGGLE_MENU = 'TOGGLE_MENU';
export const CLOSE_MENU = 'CLOSE_MENU';
export const OPEN_MENU = 'OPEN_MENU';
export const LOADING = 'LOADING';
export const SET_USER = 'SET_USER';

export const ADD_FAVORITE_ANIMAL = 'ADD_FAVORITE_ANIMAL';
export const REMOVE_FAVORITE_ANIMAL = 'REMOVE_FAVORITE_ANIMAL';

// SEARCH FILTERS
export const UPDATE_SEARCH_TYPE = 'UPDATE_SEARCH_TYPE';
export const UPDATE_SEARCH_SIZE = 'UPDATE_SEARCH_SIZE';
export const UPDATE_SEARCH_GENDER = 'UPDATE_SEARCH_GENDER';
export const UPDATE_SEARCH_AGE_GROUP = 'UPDATE_SEARCH_AGE_GROUP';
export const UPDATE_SEARCH_CITY = 'UPDATE_SEARCH_CITY';
export const RESET_SEARCH_FILTER = 'RESET_SEARCH_FILTER';
export const CHECK_NEXT_PAGE = 'CHECK_NEXT_PAGE';