import { library } from '@fortawesome/fontawesome-svg-core'
import { 
  faSearch, 
  faCat, 
  faDog, 
  faInfoCircle, 
  faSignOutAlt, 
  faPaw,
  faArrowLeft,
  faArrowRight,
  faBriefcaseMedical,
  faSyringe,
  faHeart,
  faUser,
  faChevronLeft,
  faChevronRight,
  faMars,
  faVenus,
  faPills,
  faStarOfLife,
  faImages,
  faImage,
  faTrashAlt,
  faQuoteRight,
  faQuoteLeft,
  faMapMarkerAlt,
  faHome,
  faCheck,
  faClock,
} from '@fortawesome/free-solid-svg-icons'

const bindIcons = () => library.add(
  faSearch, 
  faCat, 
  faDog, 
  faInfoCircle, 
  faSignOutAlt, 
  faPaw, 
  faArrowLeft,
  faArrowRight,
  faBriefcaseMedical,
  faSyringe,
  faHeart,
  faUser,
  faChevronLeft,
  faChevronRight,
  faMars,
  faVenus,
  faPills,
  faStarOfLife,
  faImages,
  faImage,
  faTrashAlt,
  faQuoteLeft,
  faQuoteRight,
  faMapMarkerAlt,
  faHome,
  faCheck,
  faClock
);

export default bindIcons();